# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\WinPython-64bit-3.5.1.3\notebooks\FIRDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.impulseMatplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.impulseMatplotlibwidget.setGeometry(QtCore.QRect(10, 180, 491, 251))
        self.impulseMatplotlibwidget.setAutoFillBackground(False)
        self.impulseMatplotlibwidget.setStyleSheet(_fromUtf8("MatplotlibWidget{\n"
"border-width: 0px;\n"
"}\n"
""))
        self.impulseMatplotlibwidget.setObjectName(_fromUtf8("impulseMatplotlibwidget"))
        self.freqResponseMatplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.freqResponseMatplotlibwidget.setGeometry(QtCore.QRect(10, 430, 1001, 301))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.freqResponseMatplotlibwidget.setFont(font)
        self.freqResponseMatplotlibwidget.setStyleSheet(_fromUtf8("MatplotlibWidget{\n"
"border-width: 0px;\n"
"}"))
        self.freqResponseMatplotlibwidget.setObjectName(_fromUtf8("freqResponseMatplotlibwidget"))
        self.bandStartHorizontalSlider = QtGui.QSlider(self.centralwidget)
        self.bandStartHorizontalSlider.setGeometry(QtCore.QRect(50, 50, 161, 16))
        self.bandStartHorizontalSlider.setMaximum(50)
        self.bandStartHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bandStartHorizontalSlider.setObjectName(_fromUtf8("bandStartHorizontalSlider"))
        self.bandEndHorizontalSlider = QtGui.QSlider(self.centralwidget)
        self.bandEndHorizontalSlider.setGeometry(QtCore.QRect(50, 100, 161, 16))
        self.bandEndHorizontalSlider.setMaximum(50)
        self.bandEndHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bandEndHorizontalSlider.setObjectName(_fromUtf8("bandEndHorizontalSlider"))
        self.bandLevelVerticalSlider = QtGui.QSlider(self.centralwidget)
        self.bandLevelVerticalSlider.setGeometry(QtCore.QRect(230, 50, 20, 71))
        self.bandLevelVerticalSlider.setMaximum(100)
        self.bandLevelVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.bandLevelVerticalSlider.setObjectName(_fromUtf8("bandLevelVerticalSlider"))
        self.bandStart = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandStart.setGeometry(QtCore.QRect(50, 130, 62, 22))
        self.bandStart.setDecimals(4)
        self.bandStart.setMaximum(0.5)
        self.bandStart.setSingleStep(0.01)
        self.bandStart.setObjectName(_fromUtf8("bandStart"))
        self.bandEnd = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandEnd.setGeometry(QtCore.QRect(120, 130, 62, 22))
        self.bandEnd.setDecimals(4)
        self.bandEnd.setMaximum(0.5)
        self.bandEnd.setSingleStep(0.01)
        self.bandEnd.setObjectName(_fromUtf8("bandEnd"))
        self.bandLevel = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandLevel.setGeometry(QtCore.QRect(190, 130, 62, 22))
        self.bandLevel.setDecimals(4)
        self.bandLevel.setMaximum(1.0)
        self.bandLevel.setSingleStep(0.01)
        self.bandLevel.setObjectName(_fromUtf8("bandLevel"))
        self.bandEnd_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandEnd_2.setGeometry(QtCore.QRect(360, 130, 62, 22))
        self.bandEnd_2.setDecimals(4)
        self.bandEnd_2.setMaximum(0.5)
        self.bandEnd_2.setSingleStep(0.01)
        self.bandEnd_2.setObjectName(_fromUtf8("bandEnd_2"))
        self.bandEndHorizontalSlider_2 = QtGui.QSlider(self.centralwidget)
        self.bandEndHorizontalSlider_2.setGeometry(QtCore.QRect(290, 100, 161, 16))
        self.bandEndHorizontalSlider_2.setMaximum(50)
        self.bandEndHorizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.bandEndHorizontalSlider_2.setObjectName(_fromUtf8("bandEndHorizontalSlider_2"))
        self.bandLevelVerticalSlider_2 = QtGui.QSlider(self.centralwidget)
        self.bandLevelVerticalSlider_2.setGeometry(QtCore.QRect(470, 50, 20, 71))
        self.bandLevelVerticalSlider_2.setMaximum(100)
        self.bandLevelVerticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.bandLevelVerticalSlider_2.setObjectName(_fromUtf8("bandLevelVerticalSlider_2"))
        self.bandLevel_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandLevel_2.setGeometry(QtCore.QRect(430, 130, 62, 22))
        self.bandLevel_2.setDecimals(4)
        self.bandLevel_2.setMaximum(1.0)
        self.bandLevel_2.setSingleStep(0.01)
        self.bandLevel_2.setObjectName(_fromUtf8("bandLevel_2"))
        self.bandStart_2 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandStart_2.setGeometry(QtCore.QRect(290, 130, 62, 22))
        self.bandStart_2.setDecimals(4)
        self.bandStart_2.setMaximum(0.5)
        self.bandStart_2.setSingleStep(0.01)
        self.bandStart_2.setObjectName(_fromUtf8("bandStart_2"))
        self.bandStartHorizontalSlider_2 = QtGui.QSlider(self.centralwidget)
        self.bandStartHorizontalSlider_2.setGeometry(QtCore.QRect(290, 50, 161, 16))
        self.bandStartHorizontalSlider_2.setMaximum(50)
        self.bandStartHorizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.bandStartHorizontalSlider_2.setObjectName(_fromUtf8("bandStartHorizontalSlider_2"))
        self.bandEnd_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandEnd_3.setGeometry(QtCore.QRect(600, 130, 62, 22))
        self.bandEnd_3.setDecimals(4)
        self.bandEnd_3.setMaximum(0.5)
        self.bandEnd_3.setSingleStep(0.01)
        self.bandEnd_3.setObjectName(_fromUtf8("bandEnd_3"))
        self.bandEndHorizontalSlider_3 = QtGui.QSlider(self.centralwidget)
        self.bandEndHorizontalSlider_3.setGeometry(QtCore.QRect(530, 100, 161, 16))
        self.bandEndHorizontalSlider_3.setMaximum(50)
        self.bandEndHorizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.bandEndHorizontalSlider_3.setObjectName(_fromUtf8("bandEndHorizontalSlider_3"))
        self.bandLevelVerticalSlider_3 = QtGui.QSlider(self.centralwidget)
        self.bandLevelVerticalSlider_3.setGeometry(QtCore.QRect(710, 50, 20, 71))
        self.bandLevelVerticalSlider_3.setMaximum(100)
        self.bandLevelVerticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.bandLevelVerticalSlider_3.setObjectName(_fromUtf8("bandLevelVerticalSlider_3"))
        self.bandLevel_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandLevel_3.setGeometry(QtCore.QRect(670, 130, 62, 22))
        self.bandLevel_3.setDecimals(4)
        self.bandLevel_3.setMaximum(1.0)
        self.bandLevel_3.setSingleStep(0.01)
        self.bandLevel_3.setObjectName(_fromUtf8("bandLevel_3"))
        self.bandStart_3 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandStart_3.setGeometry(QtCore.QRect(530, 130, 62, 22))
        self.bandStart_3.setDecimals(4)
        self.bandStart_3.setMaximum(0.5)
        self.bandStart_3.setSingleStep(0.01)
        self.bandStart_3.setObjectName(_fromUtf8("bandStart_3"))
        self.bandStartHorizontalSlider_3 = QtGui.QSlider(self.centralwidget)
        self.bandStartHorizontalSlider_3.setGeometry(QtCore.QRect(530, 50, 161, 16))
        self.bandStartHorizontalSlider_3.setMaximum(50)
        self.bandStartHorizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.bandStartHorizontalSlider_3.setObjectName(_fromUtf8("bandStartHorizontalSlider_3"))
        self.bandEnd_4 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandEnd_4.setGeometry(QtCore.QRect(840, 130, 62, 22))
        self.bandEnd_4.setDecimals(4)
        self.bandEnd_4.setMaximum(0.5)
        self.bandEnd_4.setSingleStep(0.01)
        self.bandEnd_4.setObjectName(_fromUtf8("bandEnd_4"))
        self.bandEndHorizontalSlider_4 = QtGui.QSlider(self.centralwidget)
        self.bandEndHorizontalSlider_4.setGeometry(QtCore.QRect(770, 100, 161, 16))
        self.bandEndHorizontalSlider_4.setMaximum(50)
        self.bandEndHorizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.bandEndHorizontalSlider_4.setObjectName(_fromUtf8("bandEndHorizontalSlider_4"))
        self.bandLevelVerticalSlider_4 = QtGui.QSlider(self.centralwidget)
        self.bandLevelVerticalSlider_4.setGeometry(QtCore.QRect(950, 50, 20, 71))
        self.bandLevelVerticalSlider_4.setMaximum(100)
        self.bandLevelVerticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.bandLevelVerticalSlider_4.setObjectName(_fromUtf8("bandLevelVerticalSlider_4"))
        self.bandLevel_4 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandLevel_4.setGeometry(QtCore.QRect(910, 130, 62, 22))
        self.bandLevel_4.setDecimals(4)
        self.bandLevel_4.setMaximum(1.0)
        self.bandLevel_4.setSingleStep(0.01)
        self.bandLevel_4.setObjectName(_fromUtf8("bandLevel_4"))
        self.bandStart_4 = QtGui.QDoubleSpinBox(self.centralwidget)
        self.bandStart_4.setGeometry(QtCore.QRect(770, 130, 62, 22))
        self.bandStart_4.setDecimals(4)
        self.bandStart_4.setMaximum(0.5)
        self.bandStart_4.setSingleStep(0.01)
        self.bandStart_4.setObjectName(_fromUtf8("bandStart_4"))
        self.bandStartHorizontalSlider_4 = QtGui.QSlider(self.centralwidget)
        self.bandStartHorizontalSlider_4.setGeometry(QtCore.QRect(770, 50, 161, 16))
        self.bandStartHorizontalSlider_4.setMaximum(50)
        self.bandStartHorizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.bandStartHorizontalSlider_4.setObjectName(_fromUtf8("bandStartHorizontalSlider_4"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 1001, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.bandsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.bandsSpinBox.setGeometry(QtCore.QRect(50, 10, 61, 22))
        self.bandsSpinBox.setMinimum(2)
        self.bandsSpinBox.setMaximum(4)
        self.bandsSpinBox.setProperty("value", 2)
        self.bandsSpinBox.setObjectName(_fromUtf8("bandsSpinBox"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 1001, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.coeffsTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.coeffsTextBrowser.setGeometry(QtCore.QRect(500, 179, 512, 251))
        self.coeffsTextBrowser.setAutoFillBackground(True)
        self.coeffsTextBrowser.setStyleSheet(_fromUtf8("QtextBrowser{\n"
"border-width: 0px;\n"
"}"))
        self.coeffsTextBrowser.setAcceptRichText(False)
        self.coeffsTextBrowser.setObjectName(_fromUtf8("coeffsTextBrowser"))
        self.tapsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.tapsSpinBox.setGeometry(QtCore.QRect(130, 10, 61, 22))
        self.tapsSpinBox.setMinimum(3)
        self.tapsSpinBox.setMaximum(511)
        self.tapsSpinBox.setProperty("value", 97)
        self.tapsSpinBox.setObjectName(_fromUtf8("tapsSpinBox"))
        self.sampleRateDoubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.sampleRateDoubleSpinBox.setGeometry(QtCore.QRect(370, 10, 81, 22))
        self.sampleRateDoubleSpinBox.setDecimals(3)
        self.sampleRateDoubleSpinBox.setMinimum(0.0)
        self.sampleRateDoubleSpinBox.setMaximum(1000000000.0)
        self.sampleRateDoubleSpinBox.setProperty("value", 1.0)
        self.sampleRateDoubleSpinBox.setObjectName(_fromUtf8("sampleRateDoubleSpinBox"))
        self.calculatePushButton = QtGui.QPushButton(self.centralwidget)
        self.calculatePushButton.setGeometry(QtCore.QRect(940, 10, 75, 23))
        self.calculatePushButton.setObjectName(_fromUtf8("calculatePushButton"))
        self.iterationsSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.iterationsSpinBox.setGeometry(QtCore.QRect(210, 10, 61, 22))
        self.iterationsSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.iterationsSpinBox.setMinimum(1)
        self.iterationsSpinBox.setMaximum(2048)
        self.iterationsSpinBox.setProperty("value", 25)
        self.iterationsSpinBox.setObjectName(_fromUtf8("iterationsSpinBox"))
        self.band1Label = QtGui.QLabel(self.centralwidget)
        self.band1Label.setGeometry(QtCore.QRect(123, 76, 46, 13))
        self.band1Label.setObjectName(_fromUtf8("band1Label"))
        self.band2Label = QtGui.QLabel(self.centralwidget)
        self.band2Label.setGeometry(QtCore.QRect(363, 76, 46, 13))
        self.band2Label.setObjectName(_fromUtf8("band2Label"))
        self.band3Label = QtGui.QLabel(self.centralwidget)
        self.band3Label.setGeometry(QtCore.QRect(603, 76, 46, 13))
        self.band3Label.setObjectName(_fromUtf8("band3Label"))
        self.band4Label = QtGui.QLabel(self.centralwidget)
        self.band4Label.setGeometry(QtCore.QRect(843, 76, 46, 13))
        self.band4Label.setObjectName(_fromUtf8("band4Label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPrototypes = QtGui.QMenu(self.menubar)
        self.menuPrototypes.setObjectName(_fromUtf8("menuPrototypes"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLowpass = QtGui.QAction(MainWindow)
        self.actionLowpass.setObjectName(_fromUtf8("actionLowpass"))
        self.actionHighpass = QtGui.QAction(MainWindow)
        self.actionHighpass.setObjectName(_fromUtf8("actionHighpass"))
        self.actionBandpass = QtGui.QAction(MainWindow)
        self.actionBandpass.setObjectName(_fromUtf8("actionBandpass"))
        self.actionBandreject = QtGui.QAction(MainWindow)
        self.actionBandreject.setObjectName(_fromUtf8("actionBandreject"))
        self.action4_band = QtGui.QAction(MainWindow)
        self.action4_band.setObjectName(_fromUtf8("action4_band"))
        self.menuPrototypes.addAction(self.actionLowpass)
        self.menuPrototypes.addAction(self.actionHighpass)
        self.menuPrototypes.addAction(self.actionBandpass)
        self.menuPrototypes.addAction(self.actionBandreject)
        self.menuPrototypes.addAction(self.action4_band)
        self.menubar.addAction(self.menuPrototypes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.impulseMatplotlibwidget.setToolTip(_translate("MainWindow", "Impulse response plot", None))
        self.freqResponseMatplotlibwidget.setToolTip(_translate("MainWindow", "Frequency response", None))
        self.bandStartHorizontalSlider.setToolTip(_translate("MainWindow", "Band 1 start", None))
        self.bandEndHorizontalSlider.setToolTip(_translate("MainWindow", "Band 1 end", None))
        self.bandLevelVerticalSlider.setToolTip(_translate("MainWindow", "Band 1 level", None))
        self.bandStart.setToolTip(_translate("MainWindow", "band 1 start", None))
        self.bandEnd.setToolTip(_translate("MainWindow", "band 1 end", None))
        self.bandLevel.setToolTip(_translate("MainWindow", "band 1 level", None))
        self.bandEnd_2.setToolTip(_translate("MainWindow", "band 2 end", None))
        self.bandEndHorizontalSlider_2.setToolTip(_translate("MainWindow", "band 2 end", None))
        self.bandLevelVerticalSlider_2.setToolTip(_translate("MainWindow", "band 2 level", None))
        self.bandLevel_2.setToolTip(_translate("MainWindow", "band 2 level", None))
        self.bandStart_2.setToolTip(_translate("MainWindow", "band 2 start", None))
        self.bandStartHorizontalSlider_2.setToolTip(_translate("MainWindow", "band 2 start", None))
        self.bandEnd_3.setToolTip(_translate("MainWindow", "band 3 end", None))
        self.bandEndHorizontalSlider_3.setToolTip(_translate("MainWindow", "band 3 end", None))
        self.bandLevelVerticalSlider_3.setToolTip(_translate("MainWindow", "band 3 level", None))
        self.bandLevel_3.setToolTip(_translate("MainWindow", "band 3 level", None))
        self.bandStart_3.setToolTip(_translate("MainWindow", "band 3 start", None))
        self.bandStartHorizontalSlider_3.setToolTip(_translate("MainWindow", "band 3 start", None))
        self.bandEnd_4.setToolTip(_translate("MainWindow", "band 4 end", None))
        self.bandEndHorizontalSlider_4.setToolTip(_translate("MainWindow", "band 4 end", None))
        self.bandLevelVerticalSlider_4.setToolTip(_translate("MainWindow", "band 4 level", None))
        self.bandLevel_4.setToolTip(_translate("MainWindow", "band 4 level", None))
        self.bandStart_4.setToolTip(_translate("MainWindow", "band 4 start", None))
        self.bandStartHorizontalSlider_4.setToolTip(_translate("MainWindow", "band 4 start", None))
        self.bandsSpinBox.setToolTip(_translate("MainWindow", "Number of bands", None))
        self.coeffsTextBrowser.setToolTip(_translate("MainWindow", "Filter coefficients", None))
        self.coeffsTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">// FIR Coefficients</p></body></html>", None))
        self.tapsSpinBox.setToolTip(_translate("MainWindow", "Number of taps", None))
        self.sampleRateDoubleSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sampling rate</p><p>(This is only used to scale the the frequency response graph\'s frequency axis.)</p><p><br/></p></body></html>", None))
        self.calculatePushButton.setToolTip(_translate("MainWindow", "calculate FIR coefficients", None))
        self.calculatePushButton.setText(_translate("MainWindow", "Calculate", None))
        self.iterationsSpinBox.setToolTip(_translate("MainWindow", "Maximum number of iterations for remez algorithm", None))
        self.band1Label.setText(_translate("MainWindow", "Band 1", None))
        self.band2Label.setText(_translate("MainWindow", "Band 2", None))
        self.band3Label.setText(_translate("MainWindow", "Band 3", None))
        self.band4Label.setText(_translate("MainWindow", "Band 4", None))
        self.menuPrototypes.setTitle(_translate("MainWindow", "Prototypes", None))
        self.actionLowpass.setText(_translate("MainWindow", "Lowpass", None))
        self.actionHighpass.setText(_translate("MainWindow", "Highpass", None))
        self.actionBandpass.setText(_translate("MainWindow", "Bandpass", None))
        self.actionBandreject.setText(_translate("MainWindow", "Bandreject", None))
        self.action4_band.setText(_translate("MainWindow", "4-band", None))

from matplotlibwidget import MatplotlibWidget
